import { v4 as uuid } from "uuid";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
import {
  air_zoom_maxfly_more_uptempo,
  air_zoom_pegasus_38,
  jordan_1_mid,
  jordan_one_low,
  jordan_one_mid_blue,
  nike_mercurial,
  nike_running_shoe,
  premier_3_FG,
  running,
  shoe,
  zoomX_streakfly,
} from "../../assests";

export const products = [
  {
    _id: uuid(),
    name: "Jordan 1 Mid",
    price: 99,
    categoryName: "jordans",
    inWishList: true,
    rating: 4,
    productImage: jordan_one_mid_blue,
  },
  {
    _id: uuid(),
    name: "Alphafly Zoom",
    price: 98,
    categoryName: "running",
    inWishList: false,
    rating: 3,
    productImage: nike_running_shoe,
  },
  {
    _id: uuid(),
    name: "jordan Mid SE",
    price: 97,
    categoryName: "jordans",
    inWishList: false,
    rating: 2,
    description:
      "Give your look an edge, in the Air Jordan 1 Mid SE.Made from premium leather throughout, it features an updated colour scheme, making a fresh play on the all-time favourite Full-grain leather in the upper provides classic style and durability, Encapsulated Air unit in the heel offers lightweight cushioning Rubber tread gives you durable traction.",
    productImage: jordan_1_mid,
  },
  {
    _id: uuid(),
    name: "Jordan Zoom",
    price: 96,
    categoryName: "jordans",
    inWishList: false,
    rating: 1,
    productImage: air_zoom_maxfly_more_uptempo,
  },
  {
    _id: uuid(),
    name: "Football Zoom",
    price: 701,
    categoryName: "football",
    inWishList: false,
    rating: 4,
    productImage: nike_mercurial,
  },
  {
    _id: uuid(),
    name: "Football Zoom",
    price: 801,
    categoryName: "football",
    inWishList: false,
    rating: 4,
    productImage: shoe,
  },
  {
    _id: uuid(),
    name: "Premier 3 FG",
    price: 901,
    categoryName: "football",
    inWishList: false,
    rating: 3,
    productImage: premier_3_FG,
  },
  {
    _id: uuid(),
    name: "Basketball Zoo",
    price: 102,
    categoryName: "basketball",
    inWishList: false,
    rating: 1,
    productImage: shoe,
  },
  {
    _id: uuid(),
    name: "Basketball Zoo",
    price: 109,
    categoryName: "basketball",
    inWishList: false,
    rating: 3,
    productImage: shoe,
  },
  {
    _id: uuid(),
    name: "Jordan 1 low",
    price: 115,
    categoryName: "jordans",
    inWishList: false,
    rating: 2,
    productImage: jordan_one_low,
  },
  {
    _id: uuid(),
    name: "zoom streakfly",
    price: 103,
    categoryName: "running",
    inWishList: false,
    rating: 3,
    productImage: zoomX_streakfly,
  },
  {
    _id: uuid(),
    name: "Walking Zoom",
    price: 100,
    categoryName: "walking",
    inWishList: false,
    rating: 4,
    productImage: shoe,
  },
  {
    _id: uuid(),
    name: "Zoom Pegasus",
    price: 100,
    categoryName: "running",
    inWishList: false,
    rating: 3,
    productImage: air_zoom_pegasus_38,
  },
];
